: https://github.com/ferreiralucas92/jokenpo


# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'
  webAppName: 'nextia'
  environmentName: 'nextia'
  vmImageName: 'ubuntu-latest'


stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        tags: |
          $(tag)


- stage: Deploy
  displayName: Deploy stage
  dependsOn: Build
  condition: succeeded()
  jobs:
  - deployment: DeployWebApp
    displayName: Deploy Web App
    environment: $(environmentName)
    pool:
      vmImage: $(vmImageName)
    strategy:
      runOnce:
        deploy:
          steps:
          - script: |
              echo "Listing contents of $(Pipeline.Workspace)"
              ls -R $(Pipeline.Workspace)
              echo "Listing contents of $(System.DefaultWorkingDirectory)"
              ls -R $(System.DefaultWorkingDirectory)
            displayName: 'Debug: List artifact paths'
          
          - task: AzureWebApp@1
            displayName: 'Azure Web App Deploy'
            inputs:
              azureSubscription: 'Azure for Students (362bb648-db8e-4428-866f-6a4b169e04d1)'
              appType: webAppLinux
              appName: $(webAppName)
              package: '$(Pipeline.Workspace)/drop/netxai-0.0.1-SNAPSHOT.jar'
